version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - ccamel
      - fredericvilcot
      - ErikssonJoakim
      - lolottetheclash
    assignees:
      - ccamel
      - fredericvilcot
      - lolottetheclash
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - ccamel
      - fredericvilcot
      - ErikssonJoakim
      - lolottetheclash
    assignees:
      - ccamel
      - fredericvilcot
      - lolottetheclash
    open-pull-requests-limit: 5
