branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: build
          scope: deps
          release: patch
        - type: build
          scope: deps-dev
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: docs
          scope: schema
          release: minor
        - type: docs
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# okp4-subql changelog"
  - - "@semantic-release/exec"
    - prepareCmd: yarn prettier CHANGELOG.md --write
  - - "@semantic-release/npm"
    - npmPublish: false
      tarballDir: "false"
  - "@semantic-release/github"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: [project.yaml]
          from: 'version: (\d+\.\d+\.\d+)'
          to: "version: ${nextRelease.version}"
          countMatches: true
          results:
            - file: project.yaml
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - project.yaml
      message: "chore(release): perform release ${nextRelease.version}"
