specVersion: 1.0.0
name: subql-okp4
version: 0.1.0
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This repository contains the SubQuery project that indexes the OKP4 blockchain.
repository: "https://github.com/okp4/subql-okp4"
schema:
  file: ./schema.graphql
network:
  chainId: okp4-nemeton-1
  endpoint:
    - https://api.testnet.okp4.network/rpc
  chainTypes:
    cosmos.base.v1beta1:
      file: ./proto/cosmos/base/v1beta1/coin.proto
      messages:
        - Coin
    cosmwasm.wasm.v1:
      file: ./proto/cosmwasm/wasm/v1/tx.proto
      messages:
        - MsgExecuteContract
        - MsgInstantiateContract
dataSources:
  - kind: cosmos/Runtime
    startBlock: 2720090
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransaction
          kind: cosmos/TransactionHandler
        - handler: handleMessage
          kind: cosmos/MessageHandler
        - handler: handleStoreObject
          kind: cosmos/MessageHandler
          filter:
            type: /cosmwasm.wasm.v1.MsgExecuteContract
            contractCall: store_object
        - handler: handleForgetObject
          kind: cosmos/MessageHandler
          filter:
            type: /cosmwasm.wasm.v1.MsgExecuteContract
            contractCall: forget_object
        - handler: handlePinObject
          kind: cosmos/MessageHandler
          filter:
            type: /cosmwasm.wasm.v1.MsgExecuteContract
            contractCall: pin_object
        - handler: handleUnpinObject
          kind: cosmos/MessageHandler
          filter:
            type: /cosmwasm.wasm.v1.MsgExecuteContract
            contractCall: unpin_object
        - handler: handleInitObjectarium
          kind: cosmos/MessageHandler
          filter:
            type: /cosmwasm.wasm.v1.MsgInstantiateContract
            contractCall: instantiate
            attributes:
              code_id: "4"
