#!/bin/sh

DB_SUBQL_NAME=${DB_SUBQL_NAME:-subql}
DB_SUBQL_USER=${DB_SUBQL_NAME:-subql}
DB_SUBQL_PASSWORD=${DB_SUBQL_NAME:-subql}

echo "🔨 Creating databases $DB_SUBQL_NAME"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOF
CREATE DATABASE $DB_SUBQL_NAME;
\connect $DB_SUBQL_NAME;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE USER $DB_SUBQL_USER WITH ENCRYPTED PASSWORD '$DB_SUBQL_USER';
GRANT ALL PRIVILEGES ON DATABASE $DB_SUBQL_NAME TO $DB_SUBQL_USER;
EOF
