name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-yarn:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 16.19

      - name: Install subql/cli
        run: |
          npm install -g @subql/cli@3.2.0

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Generate code
        run: |
          yarn codegen

      - name: Build project
        run: |
          yarn build
