name: Test

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-subql:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: 18.18
          cache: yarn

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Generate code
        run: |
          yarn codegen

      - name: Test project
        run: |
          yarn test

  test-docker-compose:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: 18.18
          cache: yarn

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Generate code
        run: |
          yarn codegen

      - name: Build project
        run: |
          yarn build

      - name: Start Docker Compose
        uses: isbang/compose-action@v1.5.1
        timeout-minutes: 5
